// <auto-generated />
using System;
using GameFrameAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameFrameAPI.Migrations
{
    [DbContext(typeof(GamedleDBContext))]
    [Migration("20220427210453_more_games_1")]
    partial class more_games_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("GameFrameAPI.Entities.DailyGame", b =>
                {
                    b.Property<int>("DailyGameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.HasKey("DailyGameID");

                    b.HasIndex("GameId");

                    b.ToTable("DailyGames");
                });

            modelBuilder.Entity("GameFrameAPI.Entities.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CopiesSold")
                        .HasColumnType("int");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("PlatformId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 17001,
                            CopiesSold = 18000000,
                            GameName = "Super Mario Bros. 3",
                            PlatformId = 17,
                            Year = 17001
                        },
                        new
                        {
                            GameId = 17002,
                            CopiesSold = 3500000,
                            GameName = "Kung Fu",
                            PlatformId = 17,
                            Year = 17002
                        },
                        new
                        {
                            GameId = 17003,
                            CopiesSold = 2000000,
                            GameName = "Punch Out",
                            PlatformId = 17,
                            Year = 17003
                        },
                        new
                        {
                            GameId = 21001,
                            CopiesSold = 6000000,
                            GameName = "Sonic 2",
                            PlatformId = 21,
                            Year = 21001
                        },
                        new
                        {
                            GameId = 17004,
                            CopiesSold = 2730000,
                            GameName = "Metroid",
                            PlatformId = 17,
                            Year = 17004
                        },
                        new
                        {
                            GameId = 17005,
                            CopiesSold = 1570000,
                            GameName = "Excitebike",
                            PlatformId = 17,
                            Year = 17005
                        },
                        new
                        {
                            GameId = 23001,
                            CopiesSold = 4610000,
                            GameName = "Legend of Zelda - Link to the Past",
                            PlatformId = 23,
                            Year = 23001
                        },
                        new
                        {
                            GameId = 17006,
                            CopiesSold = 8000000,
                            GameName = "Tetris",
                            PlatformId = 17,
                            Year = 17006
                        },
                        new
                        {
                            GameId = 23003,
                            GameName = "Chrono Trigger",
                            PlatformId = 23,
                            Year = 23003
                        },
                        new
                        {
                            GameId = 17007,
                            GameName = "Dragon Warrior 3",
                            PlatformId = 17,
                            Year = 17007
                        },
                        new
                        {
                            GameId = 17008,
                            GameName = "Legend of Zelda",
                            PlatformId = 17,
                            Year = 17008
                        },
                        new
                        {
                            GameId = 17009,
                            GameName = "RC Pro Am",
                            PlatformId = 17,
                            Year = 17009
                        },
                        new
                        {
                            GameId = 17012,
                            GameName = "Mega Man 2",
                            PlatformId = 17,
                            Year = 17012
                        },
                        new
                        {
                            GameId = 17013,
                            GameName = "Duck Tales",
                            PlatformId = 17,
                            Year = 17013
                        },
                        new
                        {
                            GameId = 17025,
                            GameName = "Bad Dudes",
                            PlatformId = 17,
                            Year = 17025
                        },
                        new
                        {
                            GameId = 21002,
                            GameName = "Aladdin",
                            PlatformId = 21,
                            Year = 21002
                        },
                        new
                        {
                            GameId = 17026,
                            GameName = "Contra",
                            PlatformId = 17,
                            Year = 17026
                        },
                        new
                        {
                            GameId = 17024,
                            GameName = "Top Gun",
                            PlatformId = 17,
                            Year = 17024
                        },
                        new
                        {
                            GameId = 23004,
                            GameName = "F-Zero",
                            PlatformId = 23,
                            Year = 23004
                        },
                        new
                        {
                            GameId = 17027,
                            GameName = "TMNT 2",
                            PlatformId = 17,
                            Year = 17027
                        });
                });

            modelBuilder.Entity("GameFrameAPI.Entities.Platform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ConsoleGeneration")
                        .HasColumnType("int");

                    b.Property<string>("PlatformAcronym")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformCompany")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnitsSold")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("PlatformId");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            PlatformId = 10,
                            ConsoleGeneration = 1,
                            PlatformAcronym = "Odyssey 1",
                            PlatformCompany = "Magnavox",
                            PlatformName = "Magnavox Odyssey",
                            UnitsSold = 350000,
                            Year = 1972
                        },
                        new
                        {
                            PlatformId = 11,
                            ConsoleGeneration = 1,
                            PlatformAcronym = "Pong",
                            PlatformCompany = "Atari",
                            PlatformName = "Home Pong",
                            UnitsSold = 200000,
                            Year = 1975
                        },
                        new
                        {
                            PlatformId = 12,
                            ConsoleGeneration = 2,
                            PlatformAcronym = "Atari 2600",
                            PlatformCompany = "Atari",
                            PlatformName = "Atari Video Computer System",
                            UnitsSold = 30000000,
                            Year = 1977
                        },
                        new
                        {
                            PlatformId = 13,
                            ConsoleGeneration = 2,
                            PlatformAcronym = "Odyssey 2",
                            PlatformCompany = "Magnavox",
                            PlatformName = "Magnavox Odyssey 2",
                            UnitsSold = 2000000,
                            Year = 1979
                        },
                        new
                        {
                            PlatformId = 14,
                            ConsoleGeneration = 2,
                            PlatformAcronym = "Intellivision",
                            PlatformCompany = "Mattel",
                            PlatformName = "Intellivision",
                            UnitsSold = 3000000,
                            Year = 1980
                        },
                        new
                        {
                            PlatformId = 15,
                            ConsoleGeneration = 2,
                            PlatformAcronym = "Colecovision",
                            PlatformCompany = "CBS Electronics",
                            PlatformName = "Colecovision",
                            UnitsSold = 2000000,
                            Year = 1982
                        },
                        new
                        {
                            PlatformId = 16,
                            ConsoleGeneration = 2,
                            PlatformAcronym = "Atari 5200",
                            PlatformCompany = "Atari",
                            PlatformName = "Atari 5200 Supersystem",
                            UnitsSold = 1400000,
                            Year = 1982
                        },
                        new
                        {
                            PlatformId = 17,
                            ConsoleGeneration = 3,
                            PlatformAcronym = "NES",
                            PlatformCompany = "Nintendo",
                            PlatformName = "Nintendo Entertainment System",
                            UnitsSold = 61910000,
                            Year = 1983
                        },
                        new
                        {
                            PlatformId = 18,
                            ConsoleGeneration = 3,
                            PlatformAcronym = "Sega Master System",
                            PlatformCompany = "Sega",
                            PlatformName = "Sega Master System",
                            UnitsSold = 13000000,
                            Year = 1985
                        },
                        new
                        {
                            PlatformId = 19,
                            ConsoleGeneration = 3,
                            PlatformAcronym = "Atari 7800",
                            PlatformCompany = "Atari",
                            PlatformName = "Atari 7800 Pro System",
                            UnitsSold = 3770000,
                            Year = 1986
                        },
                        new
                        {
                            PlatformId = 20,
                            ConsoleGeneration = 4,
                            PlatformAcronym = "TurboGrafx-16",
                            PlatformCompany = "NEC Home Electronics",
                            PlatformName = "TurboGrafx-16",
                            UnitsSold = 5800000,
                            Year = 1987
                        },
                        new
                        {
                            PlatformId = 21,
                            ConsoleGeneration = 4,
                            PlatformAcronym = "Genesis",
                            PlatformCompany = "Sega",
                            PlatformName = "Sega Genesis",
                            UnitsSold = 30750000,
                            Year = 1988
                        },
                        new
                        {
                            PlatformId = 22,
                            ConsoleGeneration = 4,
                            PlatformAcronym = "Neo Geo",
                            PlatformCompany = "SNK Corporation",
                            PlatformName = "Neo Geo",
                            UnitsSold = 980000,
                            Year = 1990
                        },
                        new
                        {
                            PlatformId = 23,
                            ConsoleGeneration = 4,
                            PlatformAcronym = "SNES",
                            PlatformCompany = "Nintendo",
                            PlatformName = "Super Nintendo Entertainment System",
                            UnitsSold = 49100000,
                            Year = 1990
                        },
                        new
                        {
                            PlatformId = 24,
                            ConsoleGeneration = 5,
                            PlatformAcronym = "Jaguar",
                            PlatformCompany = "Atari",
                            PlatformName = "Jaguar",
                            UnitsSold = 250000,
                            Year = 1993
                        },
                        new
                        {
                            PlatformId = 25,
                            ConsoleGeneration = 5,
                            PlatformAcronym = "3D0",
                            PlatformCompany = "3DO Company",
                            PlatformName = "3DO",
                            UnitsSold = 2000000,
                            Year = 1993
                        },
                        new
                        {
                            PlatformId = 26,
                            ConsoleGeneration = 5,
                            PlatformAcronym = "Sega Saturn",
                            PlatformCompany = "Sega",
                            PlatformName = "Sega Saturn",
                            UnitsSold = 9260000,
                            Year = 1994
                        },
                        new
                        {
                            PlatformId = 27,
                            ConsoleGeneration = 5,
                            PlatformAcronym = "PS1",
                            PlatformCompany = "Sony",
                            PlatformName = "Play Station",
                            UnitsSold = 102490000,
                            Year = 1994
                        },
                        new
                        {
                            PlatformId = 28,
                            ConsoleGeneration = 5,
                            PlatformAcronym = "N64",
                            PlatformCompany = "Nintendo",
                            PlatformName = "Nintendo 64",
                            UnitsSold = 329360000,
                            Year = 1996
                        },
                        new
                        {
                            PlatformId = 29,
                            ConsoleGeneration = 6,
                            PlatformAcronym = "Dreamcast",
                            PlatformCompany = "Sega",
                            PlatformName = "Sega Dreamcast",
                            UnitsSold = 9130000,
                            Year = 1998
                        },
                        new
                        {
                            PlatformId = 30,
                            ConsoleGeneration = 6,
                            PlatformAcronym = "PS2",
                            PlatformCompany = "Sony",
                            PlatformName = "Play Station 2",
                            UnitsSold = 155000000,
                            Year = 2000
                        },
                        new
                        {
                            PlatformId = 31,
                            ConsoleGeneration = 6,
                            PlatformAcronym = "GameCube",
                            PlatformCompany = "Nintendo",
                            PlatformName = "GameCube",
                            UnitsSold = 21740000,
                            Year = 2001
                        },
                        new
                        {
                            PlatformId = 32,
                            ConsoleGeneration = 6,
                            PlatformAcronym = "Xbox",
                            PlatformCompany = "Microsoft",
                            PlatformName = "Xbox",
                            UnitsSold = 24000000,
                            Year = 2002
                        },
                        new
                        {
                            PlatformId = 33,
                            ConsoleGeneration = 7,
                            PlatformAcronym = "Xbox 360",
                            PlatformCompany = "Microsoft",
                            PlatformName = "Xbox 360",
                            UnitsSold = 84700000,
                            Year = 2005
                        },
                        new
                        {
                            PlatformId = 34,
                            ConsoleGeneration = 7,
                            PlatformAcronym = "PS3",
                            PlatformCompany = "Sony",
                            PlatformName = "Play Station 3",
                            UnitsSold = 87400000,
                            Year = 2006
                        },
                        new
                        {
                            PlatformId = 35,
                            ConsoleGeneration = 7,
                            PlatformAcronym = "Wii",
                            PlatformCompany = "Nintendo",
                            PlatformName = "Wii",
                            UnitsSold = 101630000,
                            Year = 2006
                        },
                        new
                        {
                            PlatformId = 36,
                            ConsoleGeneration = 8,
                            PlatformAcronym = "Wii U",
                            PlatformCompany = "Nintendo",
                            PlatformName = "Wii U",
                            UnitsSold = 13560000,
                            Year = 2012
                        },
                        new
                        {
                            PlatformId = 37,
                            ConsoleGeneration = 8,
                            PlatformAcronym = "Nintendo Switch",
                            PlatformCompany = "Nintendo",
                            PlatformName = "Nintendo Switch",
                            UnitsSold = 103540000,
                            Year = 2017
                        },
                        new
                        {
                            PlatformId = 38,
                            ConsoleGeneration = 8,
                            PlatformAcronym = "PS4",
                            PlatformCompany = "Sony",
                            PlatformName = "Play Station 4",
                            UnitsSold = 116900000,
                            Year = 2013
                        },
                        new
                        {
                            PlatformId = 39,
                            ConsoleGeneration = 8,
                            PlatformAcronym = "Xbox One",
                            PlatformCompany = "Microsoft",
                            PlatformName = "Xbox One",
                            UnitsSold = 51000000,
                            Year = 2013
                        },
                        new
                        {
                            PlatformId = 40,
                            ConsoleGeneration = 9,
                            PlatformAcronym = "PS5",
                            PlatformCompany = "Sony",
                            PlatformName = "Play Station 5",
                            UnitsSold = 17300000,
                            Year = 2020
                        },
                        new
                        {
                            PlatformId = 41,
                            ConsoleGeneration = 9,
                            PlatformAcronym = "Xbox X-S",
                            PlatformCompany = "Microsoft",
                            PlatformName = "Xbox Series X and Series S",
                            UnitsSold = 12000000,
                            Year = 2020
                        });
                });

            modelBuilder.Entity("GameFrameAPI.Entities.Screenshot", b =>
                {
                    b.Property<int>("ScreenshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.HasKey("ScreenshotId");

                    b.HasIndex("GameId");

                    b.ToTable("Screenshots");

                    b.HasData(
                        new
                        {
                            ScreenshotId = 1,
                            GameId = 17001,
                            ImageURL = "https://drive.google.com/thumbnail?id=1t9Fe-WybuXJCuXMKgSL-wU22ByckeUXs",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 2,
                            GameId = 17001,
                            ImageURL = "https://drive.google.com/thumbnail?id=1Xqw6vvoDkeWrdcGo0R-45_BAz_jTh8Fy",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 3,
                            GameId = 17001,
                            ImageURL = "https://drive.google.com/thumbnail?id=1_qdkOzG2Oq80V0iwIgpn09vkD4aU2fHr",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 4,
                            GameId = 17001,
                            ImageURL = "https://drive.google.com/thumbnail?id=1OBQRFhFdQG_X89sJca3tqNIA955xQW4Z",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 5,
                            GameId = 17001,
                            ImageURL = "https://drive.google.com/thumbnail?id=1A4xbZwOSPyehQX0NOvC3RIt-6mJAyMlC",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 6,
                            GameId = 17001,
                            ImageURL = "https://drive.google.com/thumbnail?id=11ld7S6JEVEmrF5XsxJISUu5T3tuRgW5h",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 7,
                            GameId = 17002,
                            ImageURL = "https://drive.google.com/thumbnail?id=1OxfT0N7v-V4gA3Mtq7x6MsoK6M_ZH3cQ",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 8,
                            GameId = 17002,
                            ImageURL = "https://drive.google.com/thumbnail?id=1qnwyFLkJtn5jyEvzck3NebpdTXxONjiS",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 9,
                            GameId = 17002,
                            ImageURL = "https://drive.google.com/thumbnail?id=1LO88VtMtmLU0ukfAPgFAVWocU0K8yO_n",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 10,
                            GameId = 17002,
                            ImageURL = "https://drive.google.com/thumbnail?id=1SmgWwN-CG0gcv2Pzz71MBuXPCPPwqZxN",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 11,
                            GameId = 17002,
                            ImageURL = "https://drive.google.com/thumbnail?id=1yN-wD3gUhM3L0UWGv5Pcm3Xg98xvrd4A",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 12,
                            GameId = 17002,
                            ImageURL = "https://drive.google.com/thumbnail?id=1Xx1LLL2JevBqogSv7VC-WJJjpSizmUpw",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 13,
                            GameId = 17003,
                            ImageURL = "https://drive.google.com/thumbnail?id=13UroXdqyu0ac0ZElXpxaO3ijIwioMKvs",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 14,
                            GameId = 17003,
                            ImageURL = "https://drive.google.com/thumbnail?id=1-sDefBKVf0CP8XxtL2q_fwTwHdYnw0UL",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 15,
                            GameId = 17003,
                            ImageURL = "https://drive.google.com/thumbnail?id=1JPzRM9Fn-VVa1pmTEl6QLwmCyvcJ1e5Q",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 16,
                            GameId = 17003,
                            ImageURL = "https://drive.google.com/thumbnail?id=1CSqljvIoWkqp5DVi9eCGtfd5vrattFoL",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 17,
                            GameId = 17003,
                            ImageURL = "https://drive.google.com/thumbnail?id=13sG4hr7Mln4A_j8opP987-j7NdEnsn2j",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 18,
                            GameId = 17003,
                            ImageURL = "https://drive.google.com/thumbnail?id=162_hSiWlMuWu6aZ9sj3waiiiIQruzPx_",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 19,
                            GameId = 21001,
                            ImageURL = "https://drive.google.com/thumbnail?id=1nf7NOmlSejuavIwQ19fLG_ebxLtpVcKF",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 20,
                            GameId = 21001,
                            ImageURL = "https://drive.google.com/thumbnail?id=1gNC99vzAIXb2NC8iLNBA2gMAgGeIoqGo",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 21,
                            GameId = 21001,
                            ImageURL = "https://drive.google.com/thumbnail?id=184zYWXEWTrDACgKq1wDNoXR_tbrabvfb",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 22,
                            GameId = 21001,
                            ImageURL = "https://drive.google.com/thumbnail?id=1P7ykfTpOI5OueiEZms-dInN54arkxfwa",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 23,
                            GameId = 21001,
                            ImageURL = "https://drive.google.com/thumbnail?id=1jm10NfvMG7B_aPjvAswR9LmRSXzlpr6T",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 24,
                            GameId = 21001,
                            ImageURL = "https://drive.google.com/thumbnail?id=18YWNKL02BHXXRIh90WcZd6s6izZ_WnUy",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 25,
                            GameId = 17004,
                            ImageURL = "https://drive.google.com/thumbnail?id=1a3auKkdGovUSdg9WhkMXa5ip8ztA8jfZ",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 26,
                            GameId = 17004,
                            ImageURL = "https://drive.google.com/thumbnail?id=1t0vDMtE2IHwdaQfO12FsoX2nrgWBZ7mu",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 27,
                            GameId = 17004,
                            ImageURL = "https://drive.google.com/thumbnail?id=11zw_UotjOIDrVdn0rSW9ZNHUsgP7Ws-H",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 28,
                            GameId = 17004,
                            ImageURL = "https://drive.google.com/thumbnail?id=1ekPT6hts0XleUxQapCM7XFgMuFP4uo02",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 29,
                            GameId = 17004,
                            ImageURL = "https://drive.google.com/thumbnail?id=1_XBR6xRR7bMUHQUGCsOm-MXjSQOQX5qb",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 30,
                            GameId = 17004,
                            ImageURL = "https://drive.google.com/thumbnail?id=1E7zud3uWtAx9PG9daFe8HkwIdHzpm-1_",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 31,
                            GameId = 17005,
                            ImageURL = "https://drive.google.com/thumbnail?id=1B7T_GvOxmSt3P0ygcIPTAawCcddOjfDM",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 32,
                            GameId = 17005,
                            ImageURL = "https://drive.google.com/thumbnail?id=1153NWxy8MPDbfW4oPdKObVza11JCsp4d",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 33,
                            GameId = 17005,
                            ImageURL = "https://drive.google.com/thumbnail?id=1FfSsJuyD9VfIT0B-CloA5kgf1nG-tVcv",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 34,
                            GameId = 17005,
                            ImageURL = "https://drive.google.com/thumbnail?id=1wkXgS0gOECrUxxXKVahEn5ZxHIrk-WlT",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 35,
                            GameId = 17005,
                            ImageURL = "https://drive.google.com/thumbnail?id=15F5m47vg-x6945E70GXIfB6pxUg_c7fW",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 36,
                            GameId = 17005,
                            ImageURL = "https://drive.google.com/thumbnail?id=1ra7bO94jnCrrHsFP8FppEeQWUekPncc7",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 37,
                            GameId = 23001,
                            ImageURL = "https://drive.google.com/thumbnail?id=1GEtNogEzH8hU2YrLJegbiGSBd8hK8uqO",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 38,
                            GameId = 23001,
                            ImageURL = "https://drive.google.com/thumbnail?id=1No9SvpnBJswgYit9F35NnI6Gm0RtM6rR",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 39,
                            GameId = 23001,
                            ImageURL = "https://drive.google.com/thumbnail?id=1N8MHXPHxfVAKOSS1rqEvD9ohahUHL6aF",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 40,
                            GameId = 23001,
                            ImageURL = "https://drive.google.com/thumbnail?id=19DWIbOrtIBwXmJ9f4oK53YI98j0iiLO1",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 41,
                            GameId = 23001,
                            ImageURL = "https://drive.google.com/thumbnail?id=174ChzOfNY7HMnbJqz0GU_XVww9mo5Dnr",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 42,
                            GameId = 23001,
                            ImageURL = "https://drive.google.com/thumbnail?id=1q88TCI0nb9aiW_je0d5SEaXGSC0Udbxs",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 43,
                            GameId = 17006,
                            ImageURL = "https://drive.google.com/thumbnail?id=1Ab-oGcvTGB5iTaE-lmqlSxSnTvfG6icW",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 44,
                            GameId = 17006,
                            ImageURL = "https://drive.google.com/thumbnail?id=1kafqyKB52SvwJgQ5vzDnvpJ5H4l7glrC",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 45,
                            GameId = 17006,
                            ImageURL = "https://drive.google.com/thumbnail?id=1DA8sZcAsjV7uUqoCR31bNXxl3uThanHU",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 46,
                            GameId = 17006,
                            ImageURL = "https://drive.google.com/thumbnail?id=1ST9XL0AiwZt6cGFVV07L0tuZhw9T1S7H",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 47,
                            GameId = 17006,
                            ImageURL = "https://drive.google.com/thumbnail?id=1R3meyuq6rsKXLA__PbpHbHt8lWLZ8Zpd",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 48,
                            GameId = 17006,
                            ImageURL = "https://drive.google.com/thumbnail?id=1x2556ctthuHYoDbvbSrv0xXzYGMW1SEn",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 49,
                            GameId = 23003,
                            ImageURL = "https://drive.google.com/thumbnail?id=1neUcrBd5SFB0HfsnhPvJAGlNFYcWv3gd",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 50,
                            GameId = 23003,
                            ImageURL = "https://drive.google.com/thumbnail?id=1ZJV1OA1mWR-uMD7Lk87pBC4HuHLHO3IR",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 51,
                            GameId = 23003,
                            ImageURL = "https://drive.google.com/thumbnail?id=1ct2zd02oMlSGV05s2iWq6ad7TKsgHwdt",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 52,
                            GameId = 23003,
                            ImageURL = "https://drive.google.com/thumbnail?id=1iykD4B7tzJ9FMFScJsHmsvW9wI5Radq_",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 53,
                            GameId = 23003,
                            ImageURL = "https://drive.google.com/thumbnail?id=1H0gpPAC5vcU6HBB785rdGEWpZ-84erqj",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 54,
                            GameId = 23003,
                            ImageURL = "https://drive.google.com/thumbnail?id=1QAdA43V_AHN_Gh7nyR4rgXKEvtLM2EkS",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 55,
                            GameId = 17007,
                            ImageURL = "https://drive.google.com/thumbnail?id=1MzWwRoH8lpsVjwI8HeSgbyuN02wt_IR_",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 56,
                            GameId = 17007,
                            ImageURL = "https://drive.google.com/thumbnail?id=1v-2JaqdxtkOXl_ZydVWI1uzs7iwLcdT0",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 57,
                            GameId = 17007,
                            ImageURL = "https://drive.google.com/thumbnail?id=1oek_1jooE1oVliJE3vaTeVK1V4pEXlCL",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 58,
                            GameId = 17007,
                            ImageURL = "https://drive.google.com/thumbnail?id=1_H0NoE0DDpzwZQHnjqfDhACgFHxDrwYC",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 59,
                            GameId = 17007,
                            ImageURL = "https://drive.google.com/thumbnail?id=1e64bYUgzIMTGR74qCVlSTXWhOSmZZElr",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 60,
                            GameId = 17007,
                            ImageURL = "https://drive.google.com/thumbnail?id=1B5XDhq6i1t_XYlwRi3Zxdy6TQxhA_vZd",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 61,
                            GameId = 17008,
                            ImageURL = "https://drive.google.com/thumbnail?id=1lHs8IIV2DHUglF-S6p0FPJSOl8zQl_1J",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 62,
                            GameId = 17008,
                            ImageURL = "https://drive.google.com/thumbnail?id=1y0VKlse2q3cRp0h0OzV_IIz_dLnz0oad",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 63,
                            GameId = 17008,
                            ImageURL = "https://drive.google.com/thumbnail?id=12mGgAFfpeiDEHn9WWQHzjDHQ47ifrliD",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 64,
                            GameId = 17008,
                            ImageURL = "https://drive.google.com/thumbnail?id=1iQYp9ffhw7qax1vFAVVG9jK5dzfX_6gJ",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 65,
                            GameId = 17008,
                            ImageURL = "https://drive.google.com/thumbnail?id=1G4c9_bLrVvplN7fzDraJCOXhzXDzIzD6",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 66,
                            GameId = 17008,
                            ImageURL = "https://drive.google.com/thumbnail?id=1tpyAOvmvgA1Y849oDrpwhTk-FwiqmcnS",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 67,
                            GameId = 17009,
                            ImageURL = "https://drive.google.com/thumbnail?id=1zPE-6WK4i2WT_RFPdM5oM0XzBPrxuJrB",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 68,
                            GameId = 17009,
                            ImageURL = "https://drive.google.com/thumbnail?id=1PQrc3T6fkfA7OaLQ_7yoayg-yoYIBKRA",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 69,
                            GameId = 17009,
                            ImageURL = "https://drive.google.com/thumbnail?id=1iSnNn1Ev9fSr90TpuO953do6AXP-8WIi",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 70,
                            GameId = 17009,
                            ImageURL = "https://drive.google.com/thumbnail?id=16r7b88M55g0kCGEIjZVkOCEMUG0J9GgM",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 71,
                            GameId = 17009,
                            ImageURL = "https://drive.google.com/thumbnail?id=1LNhTLNwEmw3203iI-OLDCLb-ixdW-zlO",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 72,
                            GameId = 17009,
                            ImageURL = "https://drive.google.com/thumbnail?id=1bzZysKu8mzxZA9vOplhzMqL6XGAgDn5v",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 73,
                            GameId = 17012,
                            ImageURL = "https://drive.google.com/thumbnail?id=1mSXLvmihh7cFkgLwtuufIaFlrod9Q3FN",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 74,
                            GameId = 17012,
                            ImageURL = "https://drive.google.com/thumbnail?id=1s1GM3pov97zyf7YALfz009OXTEoa8UDw",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 75,
                            GameId = 17012,
                            ImageURL = "https://drive.google.com/thumbnail?id=1ciBVNbW5cPsfw8ef_NQg8E6PzaZl7w81",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 76,
                            GameId = 17012,
                            ImageURL = "https://drive.google.com/thumbnail?id=1frBQgJvpCNq-0V61Ch9nU1ctv9z2wEAe",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 77,
                            GameId = 17012,
                            ImageURL = "https://drive.google.com/thumbnail?id=1Mo50nLom5ya1GSGocX6aXuzen_ABRDuC",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 78,
                            GameId = 17012,
                            ImageURL = "https://drive.google.com/thumbnail?id=1-vcfebKCY9eX0k4ratAiaQB88diz7twM",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 79,
                            GameId = 17013,
                            ImageURL = "https://drive.google.com/thumbnail?id=1FVlX8A3zYNmkGXCDPuTo4prR5P8OBsnD",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 80,
                            GameId = 17013,
                            ImageURL = "https://drive.google.com/thumbnail?id=1b5HMf-WD7DIUkXC3faznVpygAAB_bwq-",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 81,
                            GameId = 17013,
                            ImageURL = "https://drive.google.com/thumbnail?id=1udeM8a3STyYgycw85VHxvw3hl9h8XZIn",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 82,
                            GameId = 17013,
                            ImageURL = "https://drive.google.com/thumbnail?id=1nyKQIk5V65RpPrgYfGStJL2Y1YVLrKCO",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 83,
                            GameId = 17013,
                            ImageURL = "https://drive.google.com/thumbnail?id=16YZlsxdEWtwQk3FHqUK1OZVqD7lak7W3",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 84,
                            GameId = 17013,
                            ImageURL = "https://drive.google.com/thumbnail?id=1coFqbhj3s5os8P6TqOelEbwPfGR67h0a",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 85,
                            GameId = 17025,
                            ImageURL = "https://drive.google.com/thumbnail?id=1ZuDzVxN6yCxa7LDJ5nnoHrCxXFxNbwN8",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 86,
                            GameId = 17025,
                            ImageURL = "https://drive.google.com/thumbnail?id=1MEPlWUIijRFbkhSrYKlydBueQlzo40uz",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 87,
                            GameId = 17025,
                            ImageURL = "https://drive.google.com/thumbnail?id=1MoyJE0_DAVTM-xZD3XjOOUf8h0nXslgZ",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 88,
                            GameId = 17025,
                            ImageURL = "https://drive.google.com/thumbnail?id=1GfI9uiz8fJWl_1fW_LmcaNViHndy7cM5",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 89,
                            GameId = 17025,
                            ImageURL = "https://drive.google.com/thumbnail?id=1zNkThOahcYeBR7e4cf-xEdKKm5DdhUik",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 90,
                            GameId = 17025,
                            ImageURL = "https://drive.google.com/thumbnail?id=1yz3nuNb5diV5XVD2dQsRqm21_5llyGPi",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 91,
                            GameId = 21002,
                            ImageURL = "https://drive.google.com/thumbnail?id=15CR3b7JjoSYvtQTLioGWMTk2L4ByMduO",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 92,
                            GameId = 21002,
                            ImageURL = "https://drive.google.com/thumbnail?id=1IoEE2EZkGgMky6LAFXsMxAppD2qLAOQE",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 93,
                            GameId = 21002,
                            ImageURL = "https://drive.google.com/thumbnail?id=1ZCWsE1F22whXq9WkZGxgIeZRNl-z5Jiq",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 94,
                            GameId = 21002,
                            ImageURL = "https://drive.google.com/thumbnail?id=1uRY1up4wT_LLIJvSR7ZI2ymeF0x2bWxZ",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 95,
                            GameId = 21002,
                            ImageURL = "https://drive.google.com/thumbnail?id=1vY7Gb2eH_chA3v2NUoHQO3iESXhprVxh",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 96,
                            GameId = 21002,
                            ImageURL = "https://drive.google.com/thumbnail?id=1MC7LmVBfMseai5Jnu7qqK0QTHLPwXFc7",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 97,
                            GameId = 17026,
                            ImageURL = "https://drive.google.com/thumbnail?id=1GPETDYzN--iZDl4iPdw3AO-tHT57NKbc",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 98,
                            GameId = 17026,
                            ImageURL = "https://drive.google.com/thumbnail?id=1HO8m6uqC7C6aGDqUOf8QIOwJVEdGYpdj",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 99,
                            GameId = 17026,
                            ImageURL = "https://drive.google.com/thumbnail?id=1S9Jjb9p-DsoiuwQrrlL2-pii4ATYnHI3",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 100,
                            GameId = 17026,
                            ImageURL = "https://drive.google.com/thumbnail?id=17z0B4lHJ_9bT5FC3ShnNEC40z_MJmw3l",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 101,
                            GameId = 17026,
                            ImageURL = "https://drive.google.com/thumbnail?id=120GRImiHoHn7vNgi4RbecCQ9TH-07AwY",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 102,
                            GameId = 17026,
                            ImageURL = "https://drive.google.com/thumbnail?id=1-WmHhwyn30dk8-z2YagfjoBrl69ZuQpW",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 103,
                            GameId = 17024,
                            ImageURL = "https://drive.google.com/thumbnail?id=1Ixx0Q4cNysS1zmNfFaAeX7_EE4PURGdY",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 104,
                            GameId = 17024,
                            ImageURL = "https://drive.google.com/thumbnail?id=1vPC83EBH8FT8tOA7JWZKBfJfpdarW89g",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 105,
                            GameId = 17024,
                            ImageURL = "https://drive.google.com/thumbnail?id=12M05v3Ct1BTA8XZMKwYBFB0O5BcS6pby",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 106,
                            GameId = 17024,
                            ImageURL = "https://drive.google.com/thumbnail?id=1WVxRBh4pxRjxhmsNuaPlLXK6uLiVjqpA",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 107,
                            GameId = 17024,
                            ImageURL = "https://drive.google.com/thumbnail?id=1Ah64N6hfwLcxlrcubopxb9tYcJvYoQgk",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 108,
                            GameId = 17024,
                            ImageURL = "https://drive.google.com/thumbnail?id=1gX83P8OsOUyMZ2tFPGDDLxyNvWQziu40",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 109,
                            GameId = 23004,
                            ImageURL = "https://drive.google.com/thumbnail?id=1fFRpg-1PFCFmcBpkRW-RH16xPWTDp_5X",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 110,
                            GameId = 23004,
                            ImageURL = "https://drive.google.com/thumbnail?id=18Se-19YtJgSaPCdeSKRbhr_ONvIIVxm5",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 111,
                            GameId = 23004,
                            ImageURL = "https://drive.google.com/thumbnail?id=1SeH29uVbh8g-gRjM-8X3qU169Khed2Vz",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 112,
                            GameId = 23004,
                            ImageURL = "https://drive.google.com/thumbnail?id=1rHh0JvdxJpspb6mKpOFaRZ-at_CuUdxF",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 113,
                            GameId = 23004,
                            ImageURL = "https://drive.google.com/thumbnail?id=1iH605Si81b5Ogl8K3nc8SySPs_fLNUfo",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 114,
                            GameId = 23004,
                            ImageURL = "https://drive.google.com/thumbnail?id=1_EfAugpNxEWHOnOborszcF_QzVX9RkfY",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 115,
                            GameId = 17027,
                            ImageURL = "https://drive.google.com/thumbnail?id=1d2o3gq9S0o6P92e6aB52FYbjsqDHBS1O",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 116,
                            GameId = 17027,
                            ImageURL = "https://drive.google.com/thumbnail?id=1jE9gs95qj8Ho-76qNUofNfHLRMxbejn4",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 117,
                            GameId = 17027,
                            ImageURL = "https://drive.google.com/thumbnail?id=1CRMvfsxqr0T5qr_ebXtm6s9_xHlM3rDv",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 118,
                            GameId = 17027,
                            ImageURL = "https://drive.google.com/thumbnail?id=1t9kj3WG2b3wcXoCEM3fWk2EMBvIigdd3",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 119,
                            GameId = 17027,
                            ImageURL = "https://drive.google.com/thumbnail?id=1Erh2ltJf4V63xZvOze3oWZ3GCdz5RWbN",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 120,
                            GameId = 17027,
                            ImageURL = "https://drive.google.com/thumbnail?id=1cRD1M90DiATJVmZT5rwltNF7M0F9Q-3I",
                            SequenceNo = 6
                        });
                });

            modelBuilder.Entity("GameFrameAPI.Entities.DailyGame", b =>
                {
                    b.HasOne("GameFrameAPI.Entities.Game", "Game")
                        .WithMany("DailyGames")
                        .HasForeignKey("GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameFrameAPI.Entities.Game", b =>
                {
                    b.HasOne("GameFrameAPI.Entities.Platform", "Platform")
                        .WithMany("Games")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GameFrameAPI.Entities.Screenshot", b =>
                {
                    b.HasOne("GameFrameAPI.Entities.Game", "Game")
                        .WithMany("Screenshots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameFrameAPI.Entities.Game", b =>
                {
                    b.Navigation("DailyGames");

                    b.Navigation("Screenshots");
                });

            modelBuilder.Entity("GameFrameAPI.Entities.Platform", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
