// <auto-generated />
using System;
using GameFrameAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameFrameAPI.Migrations
{
    [DbContext(typeof(GamedleDBContext))]
    partial class GamedleDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("GameFrameAPI.Entities.DailyGame", b =>
                {
                    b.Property<int>("DailyGameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.HasKey("DailyGameID");

                    b.HasIndex("GameId");

                    b.ToTable("DailyGames");
                });

            modelBuilder.Entity("GameFrameAPI.Entities.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CopiesSold")
                        .HasColumnType("int");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("PlatformId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 17001,
                            CopiesSold = 18000000,
                            GameName = "Super Mario Bros. 3",
                            PlatformId = 17,
                            Year = 17001
                        },
                        new
                        {
                            GameId = 17002,
                            CopiesSold = 3500000,
                            GameName = "Kung Fu",
                            PlatformId = 17,
                            Year = 17002
                        },
                        new
                        {
                            GameId = 17003,
                            CopiesSold = 2000000,
                            GameName = "Punch Out",
                            PlatformId = 17,
                            Year = 17003
                        });
                });

            modelBuilder.Entity("GameFrameAPI.Entities.Platform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ConsoleGeneration")
                        .HasColumnType("int");

                    b.Property<string>("PlatformAcronym")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformCompany")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnitsSold")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("PlatformId");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            PlatformId = 10,
                            ConsoleGeneration = 1,
                            PlatformAcronym = "Odyssey 1",
                            PlatformCompany = "Magnavox",
                            PlatformName = "Magnavox Odyssey",
                            UnitsSold = 350000,
                            Year = 1972
                        },
                        new
                        {
                            PlatformId = 11,
                            ConsoleGeneration = 1,
                            PlatformAcronym = "Pong",
                            PlatformCompany = "Atari",
                            PlatformName = "Home Pong",
                            UnitsSold = 200000,
                            Year = 1975
                        },
                        new
                        {
                            PlatformId = 12,
                            ConsoleGeneration = 2,
                            PlatformAcronym = "Atari 2600",
                            PlatformCompany = "Atari",
                            PlatformName = "Atari Video Computer System",
                            UnitsSold = 30000000,
                            Year = 1977
                        },
                        new
                        {
                            PlatformId = 13,
                            ConsoleGeneration = 2,
                            PlatformAcronym = "Odyssey 2",
                            PlatformCompany = "Magnavox",
                            PlatformName = "Magnavox Odyssey 2",
                            UnitsSold = 2000000,
                            Year = 1979
                        },
                        new
                        {
                            PlatformId = 14,
                            ConsoleGeneration = 2,
                            PlatformAcronym = "Intellivision",
                            PlatformCompany = "Mattel",
                            PlatformName = "Intellivision",
                            UnitsSold = 3000000,
                            Year = 1980
                        },
                        new
                        {
                            PlatformId = 15,
                            ConsoleGeneration = 2,
                            PlatformAcronym = "Colecovision",
                            PlatformCompany = "CBS Electronics",
                            PlatformName = "Colecovision",
                            UnitsSold = 2000000,
                            Year = 1982
                        },
                        new
                        {
                            PlatformId = 16,
                            ConsoleGeneration = 2,
                            PlatformAcronym = "Atari 5200",
                            PlatformCompany = "Atari",
                            PlatformName = "Atari 5200 Supersystem",
                            UnitsSold = 1400000,
                            Year = 1982
                        },
                        new
                        {
                            PlatformId = 17,
                            ConsoleGeneration = 3,
                            PlatformAcronym = "NES",
                            PlatformCompany = "Nintendo",
                            PlatformName = "Nintendo Entertainment System",
                            UnitsSold = 61910000,
                            Year = 1983
                        },
                        new
                        {
                            PlatformId = 18,
                            ConsoleGeneration = 3,
                            PlatformAcronym = "Sega Master System",
                            PlatformCompany = "Sega",
                            PlatformName = "Sega Master System",
                            UnitsSold = 13000000,
                            Year = 1985
                        },
                        new
                        {
                            PlatformId = 19,
                            ConsoleGeneration = 3,
                            PlatformAcronym = "Atari 7800",
                            PlatformCompany = "Atari",
                            PlatformName = "Atari 7800 Pro System",
                            UnitsSold = 3770000,
                            Year = 1986
                        },
                        new
                        {
                            PlatformId = 20,
                            ConsoleGeneration = 4,
                            PlatformAcronym = "TurboGrafx-16",
                            PlatformCompany = "NEC Home Electronics",
                            PlatformName = "TurboGrafx-16",
                            UnitsSold = 5800000,
                            Year = 1987
                        },
                        new
                        {
                            PlatformId = 21,
                            ConsoleGeneration = 4,
                            PlatformAcronym = "Genesis",
                            PlatformCompany = "Sega",
                            PlatformName = "Sega Genesis",
                            UnitsSold = 30750000,
                            Year = 1988
                        },
                        new
                        {
                            PlatformId = 22,
                            ConsoleGeneration = 4,
                            PlatformAcronym = "Neo Geo",
                            PlatformCompany = "SNK Corporation",
                            PlatformName = "Neo Geo",
                            UnitsSold = 980000,
                            Year = 1990
                        },
                        new
                        {
                            PlatformId = 23,
                            ConsoleGeneration = 4,
                            PlatformAcronym = "SNES",
                            PlatformCompany = "Nintendo",
                            PlatformName = "Super Nintendo Entertainment System",
                            UnitsSold = 49100000,
                            Year = 1990
                        },
                        new
                        {
                            PlatformId = 24,
                            ConsoleGeneration = 5,
                            PlatformAcronym = "Jaguar",
                            PlatformCompany = "Atari",
                            PlatformName = "Jaguar",
                            UnitsSold = 250000,
                            Year = 1993
                        },
                        new
                        {
                            PlatformId = 25,
                            ConsoleGeneration = 5,
                            PlatformAcronym = "3D0",
                            PlatformCompany = "3DO Company",
                            PlatformName = "3DO",
                            UnitsSold = 2000000,
                            Year = 1993
                        },
                        new
                        {
                            PlatformId = 26,
                            ConsoleGeneration = 5,
                            PlatformAcronym = "Sega Saturn",
                            PlatformCompany = "Sega",
                            PlatformName = "Sega Saturn",
                            UnitsSold = 9260000,
                            Year = 1994
                        },
                        new
                        {
                            PlatformId = 27,
                            ConsoleGeneration = 5,
                            PlatformAcronym = "PS1",
                            PlatformCompany = "Sony",
                            PlatformName = "Play Station",
                            UnitsSold = 102490000,
                            Year = 1994
                        },
                        new
                        {
                            PlatformId = 28,
                            ConsoleGeneration = 5,
                            PlatformAcronym = "N64",
                            PlatformCompany = "Nintendo",
                            PlatformName = "Nintendo 64",
                            UnitsSold = 329360000,
                            Year = 1996
                        },
                        new
                        {
                            PlatformId = 29,
                            ConsoleGeneration = 6,
                            PlatformAcronym = "Dreamcast",
                            PlatformCompany = "Sega",
                            PlatformName = "Sega Dreamcast",
                            UnitsSold = 9130000,
                            Year = 1998
                        },
                        new
                        {
                            PlatformId = 30,
                            ConsoleGeneration = 6,
                            PlatformAcronym = "PS2",
                            PlatformCompany = "Sony",
                            PlatformName = "Play Station 2",
                            UnitsSold = 155000000,
                            Year = 2000
                        },
                        new
                        {
                            PlatformId = 31,
                            ConsoleGeneration = 6,
                            PlatformAcronym = "GameCube",
                            PlatformCompany = "Nintendo",
                            PlatformName = "GameCube",
                            UnitsSold = 21740000,
                            Year = 2001
                        },
                        new
                        {
                            PlatformId = 32,
                            ConsoleGeneration = 6,
                            PlatformAcronym = "Xbox",
                            PlatformCompany = "Microsoft",
                            PlatformName = "Xbox",
                            UnitsSold = 24000000,
                            Year = 2002
                        },
                        new
                        {
                            PlatformId = 33,
                            ConsoleGeneration = 7,
                            PlatformAcronym = "Xbox 360",
                            PlatformCompany = "Microsoft",
                            PlatformName = "Xbox 360",
                            UnitsSold = 84700000,
                            Year = 2005
                        },
                        new
                        {
                            PlatformId = 34,
                            ConsoleGeneration = 7,
                            PlatformAcronym = "PS3",
                            PlatformCompany = "Sony",
                            PlatformName = "Play Station 3",
                            UnitsSold = 87400000,
                            Year = 2006
                        },
                        new
                        {
                            PlatformId = 35,
                            ConsoleGeneration = 7,
                            PlatformAcronym = "Wii",
                            PlatformCompany = "Nintendo",
                            PlatformName = "Wii",
                            UnitsSold = 101630000,
                            Year = 2006
                        },
                        new
                        {
                            PlatformId = 36,
                            ConsoleGeneration = 8,
                            PlatformAcronym = "Wii U",
                            PlatformCompany = "Nintendo",
                            PlatformName = "Wii U",
                            UnitsSold = 13560000,
                            Year = 2012
                        },
                        new
                        {
                            PlatformId = 37,
                            ConsoleGeneration = 8,
                            PlatformAcronym = "Nintendo Switch",
                            PlatformCompany = "Nintendo",
                            PlatformName = "Nintendo Switch",
                            UnitsSold = 103540000,
                            Year = 2017
                        },
                        new
                        {
                            PlatformId = 38,
                            ConsoleGeneration = 8,
                            PlatformAcronym = "PS4",
                            PlatformCompany = "Sony",
                            PlatformName = "Play Station 4",
                            UnitsSold = 116900000,
                            Year = 2013
                        },
                        new
                        {
                            PlatformId = 39,
                            ConsoleGeneration = 8,
                            PlatformAcronym = "Xbox One",
                            PlatformCompany = "Microsoft",
                            PlatformName = "Xbox One",
                            UnitsSold = 51000000,
                            Year = 2013
                        },
                        new
                        {
                            PlatformId = 40,
                            ConsoleGeneration = 9,
                            PlatformAcronym = "PS5",
                            PlatformCompany = "Sony",
                            PlatformName = "Play Station 5",
                            UnitsSold = 17300000,
                            Year = 2020
                        },
                        new
                        {
                            PlatformId = 41,
                            ConsoleGeneration = 9,
                            PlatformAcronym = "Xbox X-S",
                            PlatformCompany = "Microsoft",
                            PlatformName = "Xbox Series X and Series S",
                            UnitsSold = 12000000,
                            Year = 2020
                        });
                });

            modelBuilder.Entity("GameFrameAPI.Entities.Screenshot", b =>
                {
                    b.Property<int>("ScreenshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.HasKey("ScreenshotId");

                    b.HasIndex("GameId");

                    b.ToTable("Screenshots");

                    b.HasData(
                        new
                        {
                            ScreenshotId = 1,
                            GameId = 17001,
                            ImageURL = "https://drive.google.com/thumbnail?id=1t9Fe-WybuXJCuXMKgSL-wU22ByckeUXs",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 2,
                            GameId = 17001,
                            ImageURL = "https://drive.google.com/thumbnail?id=1Xqw6vvoDkeWrdcGo0R-45_BAz_jTh8Fy",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 3,
                            GameId = 17001,
                            ImageURL = "https://drive.google.com/thumbnail?id=1_qdkOzG2Oq80V0iwIgpn09vkD4aU2fHr",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 4,
                            GameId = 17001,
                            ImageURL = "https://drive.google.com/thumbnail?id=1OBQRFhFdQG_X89sJca3tqNIA955xQW4Z",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 5,
                            GameId = 17001,
                            ImageURL = "https://drive.google.com/thumbnail?id=1A4xbZwOSPyehQX0NOvC3RIt-6mJAyMlC",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 6,
                            GameId = 17001,
                            ImageURL = "https://drive.google.com/thumbnail?id=11ld7S6JEVEmrF5XsxJISUu5T3tuRgW5h",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 7,
                            GameId = 17002,
                            ImageURL = "https://drive.google.com/thumbnail?id=1OxfT0N7v-V4gA3Mtq7x6MsoK6M_ZH3cQ",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 8,
                            GameId = 17002,
                            ImageURL = "https://drive.google.com/thumbnail?id=1qnwyFLkJtn5jyEvzck3NebpdTXxONjiS",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 9,
                            GameId = 17002,
                            ImageURL = "https://drive.google.com/thumbnail?id=1LO88VtMtmLU0ukfAPgFAVWocU0K8yO_n",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 10,
                            GameId = 17002,
                            ImageURL = "https://drive.google.com/thumbnail?id=1SmgWwN-CG0gcv2Pzz71MBuXPCPPwqZxN",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 11,
                            GameId = 17002,
                            ImageURL = "https://drive.google.com/thumbnail?id=1yN-wD3gUhM3L0UWGv5Pcm3Xg98xvrd4A",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 12,
                            GameId = 17002,
                            ImageURL = "https://drive.google.com/thumbnail?id=1Xx1LLL2JevBqogSv7VC-WJJjpSizmUpw",
                            SequenceNo = 6
                        },
                        new
                        {
                            ScreenshotId = 13,
                            GameId = 17003,
                            ImageURL = "https://drive.google.com/thumbnail?id=13UroXdqyu0ac0ZElXpxaO3ijIwioMKvs",
                            SequenceNo = 1
                        },
                        new
                        {
                            ScreenshotId = 14,
                            GameId = 17003,
                            ImageURL = "https://drive.google.com/thumbnail?id=1-sDefBKVf0CP8XxtL2q_fwTwHdYnw0UL",
                            SequenceNo = 2
                        },
                        new
                        {
                            ScreenshotId = 15,
                            GameId = 17003,
                            ImageURL = "https://drive.google.com/thumbnail?id=1JPzRM9Fn-VVa1pmTEl6QLwmCyvcJ1e5Q",
                            SequenceNo = 3
                        },
                        new
                        {
                            ScreenshotId = 16,
                            GameId = 17003,
                            ImageURL = "https://drive.google.com/thumbnail?id=1CSqljvIoWkqp5DVi9eCGtfd5vrattFoL",
                            SequenceNo = 4
                        },
                        new
                        {
                            ScreenshotId = 17,
                            GameId = 17003,
                            ImageURL = "https://drive.google.com/thumbnail?id=13sG4hr7Mln4A_j8opP987-j7NdEnsn2j",
                            SequenceNo = 5
                        },
                        new
                        {
                            ScreenshotId = 18,
                            GameId = 17003,
                            ImageURL = "https://drive.google.com/thumbnail?id=162_hSiWlMuWu6aZ9sj3waiiiIQruzPx_",
                            SequenceNo = 6
                        });
                });

            modelBuilder.Entity("GameFrameAPI.Entities.DailyGame", b =>
                {
                    b.HasOne("GameFrameAPI.Entities.Game", "Game")
                        .WithMany("DailyGames")
                        .HasForeignKey("GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameFrameAPI.Entities.Game", b =>
                {
                    b.HasOne("GameFrameAPI.Entities.Platform", "Platform")
                        .WithMany("Games")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GameFrameAPI.Entities.Screenshot", b =>
                {
                    b.HasOne("GameFrameAPI.Entities.Game", "Game")
                        .WithMany("Screenshots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameFrameAPI.Entities.Game", b =>
                {
                    b.Navigation("DailyGames");

                    b.Navigation("Screenshots");
                });

            modelBuilder.Entity("GameFrameAPI.Entities.Platform", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
